'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='andre-maths-quest-v1';
let saved;try{saved=JSON.parse(localStorage.getItem(KEY)||'null')}catch{}
let progress=saved&&saved.version===1?saved:{version:1,stars:0,completed:0,skills:{},calm:false};
const session=Date.now().toString(36),today=new Date().toLocaleDateString('en-CA');
let world='decimal',task,state={},help=-1,attempts=0,solved=false,mission=0,currentSkill='decimal-shade',retrySkill=null;
function record(id){return progress.skills[id]||(progress.skills[id]={seen:0,solved:0,independent:[],helped:0,misses:0,last:0});}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(progress));$('#savestatus').textContent='Progress stays on this browser.'}catch{$('#savestatus').textContent='Saving unavailable. Keep this page open.'}$('#stars').textContent='★ '+progress.stars;$('#stars').setAttribute('aria-label',progress.stars+' stars. Open discovery badges');}
function status(id){let r=record(id);let u=new Set(r.independent.map(x=>x.sig)),days=new Set(r.independent.map(x=>x.day));return u.size>=3&&days.size>=2?'Ready to review':u.size>=2?'Growing confidence':r.solved?'Practising':'Not yet explored'}
function nav(){ $('#worlds').innerHTML=WORLDS.map(w=>`<button data-world="${w.id}" class="${w.id===world?'active':''}" ${w.id===world?'aria-current="page"':''}><span class="navicon">${w.icon}</span>${w.name}<small>${SKILLS.filter(s=>s.world===w.id&&record(s.id).solved).length}/${SKILLS.filter(s=>s.world===w.id).length}</small></button>`).join('');$$('[data-world]').forEach(b=>b.onclick=()=>startWorld(b.dataset.world));let w=WORLDS.find(w=>w.id===world);$('#worldtitle').textContent=w.title;$('#worldlabel').textContent=w.tag;$('#missiondots').innerHTML=Array.from({length:5},(_,i)=>`<span class="missiondot ${i<mission?'done':''}"></span>`).join('');$('#missioncount').textContent=`${mission} / 5`;}
function pickSkill(w){let skills=SKILLS.filter(s=>s.world===w);return skills.sort((a,b)=>{let x=record(a.id),y=record(b.id);return (x.solved+x.independent.length*2)-(y.solved+y.independent.length*2)||x.last-y.last})[0].id;}
function startWorld(w,id){world=w;mission=0;retrySkill=null;loadTask(id||pickSkill(w));nav();}
function loadTask(id,level){currentSkill=id;let r=record(id);if(level==null)level=r.misses>r.solved+1?0:1;task=makeTask(id,r.seen,level);r.seen++;state={selected:[],order:[],pv:[0,0,0,0,0],rows:1,cols:1,shares:Array(task.groups||0).fill(0),bars:[0,0,0],choice:null,point:null,map:null};help=-1;attempts=0;solved=false;$('#feedback').innerHTML='';$('#check').innerHTML='Check my work <span>→</span>';$('#hint').disabled=false;$('#skillname').textContent=SKILLS.find(s=>s.id===id).name+(level===0?' · Build the basics':'');$('#tasktitle').textContent=task.prompt;$('#taskintro').textContent=task.intro;$('#activitytag').textContent=({hundred:'BUILD IT',order:'MAKE A PATH',place:'BUILD IT',array:'TEAM BUILDER',share:'SHARE IT',fraction:'SHADE IT',numberline:'JUMP TO IT',sortsteps:'CRACK THE PLAN',symmetry:'MIRROR MAKER',compose:'SHAPE BUILDER',chartbuild:'GRAPH MAKER',area:'TILE EXPLORER',choice:'THINK IT THROUGH'})[task.type]||'WORK IT OUT';$('#activity').innerHTML='';renderActivity();clearDrawing();$('#working').value='';persist();nav();}
function inputAnswer(unit=task.unit||'answer'){return `<div class="answerrow"><label for="answer">${esc(unit)}</label><input id="answer" class="answerinput" type="text" inputmode="decimal" autocomplete="off" aria-label="Your answer in ${esc(unit)}" placeholder="?" spellcheck="false"></div>`;}
function renderActivity(){let t=task,h='';
if(t.type==='hundred'){h=`<div class="activitypanel"><span class="bigvalue">${(t.target/100).toFixed(2)}</span><div class="hundredgrid">${Array.from({length:100},(_,i)=>`<button class="cell ${state.selected.includes(i)?'on':''}" data-cell="${i}" aria-label="Hundredth ${i+1}" aria-pressed="${state.selected.includes(i)}"></button>`).join('')}</div><p class="gridstatus"><strong>${state.selected.length}</strong> hundredths coloured = <strong>${(state.selected.length/100).toFixed(2)}</strong></p><div class="subtools"><button id="addten">+ 10 squares</button><button id="removeone">− 1 square</button><button id="resetactivity">Start again</button></div></div>`;}
else if(t.type==='order'||t.type==='sortsteps'){h=`<div class="activitypanel"><p class="striplabel">${t.type==='order'?'Smallest → largest':'First → last'}</p><div class="answertray">${state.order.length?state.order.map((idx,i)=>`<button data-remove="${i}">${esc(t.values[idx])}</button>`).join(''):'<span class="muted">Your path goes here</span>'}</div><div class="ordertray">${t.values.map((v,i)=>`<button class="numbertile ${state.order.includes(i)?'used':''}" data-order="${i}" ${state.order.includes(i)?'disabled':''} style="${t.type==='sortsteps'?'font-size:15px':''}">${esc(v)}</button>`).join('')}</div></div>`;}
else if(t.type==='place'){h=`<div class="activitypanel"><div class="pvboard">${['Ten thousands','Thousands','Hundreds','Tens','Ones'].map((x,i)=>`<div class="pvcol"><span>${x}</span><button data-pv="${i}" data-delta="1" aria-label="Add one ${x.toLowerCase()}">+</button><strong>${state.pv[i]}</strong><button data-pv="${i}" data-delta="-1" aria-label="Remove one ${x.toLowerCase()}">−</button></div>`).join('')}</div><p class="gridstatus">You built <strong>${pvValue().toLocaleString('en-AU')}</strong></p></div>`;}
else if(t.type==='array'){h=`<div class="activitypanel"><div class="rangecontrol"><label for="rows">Rows: <strong>${state.rows}</strong></label><input id="rows" type="range" min="1" max="10" value="${state.rows}"></div><div class="rangecontrol"><label for="cols">In each row: <strong>${state.cols}</strong></label><input id="cols" type="range" min="1" max="10" value="${state.cols}"></div><div class="array" style="grid-template-columns:repeat(${state.cols},18px)" aria-label="${state.rows} rows of ${state.cols} dots">${'<i></i>'.repeat(state.rows*state.cols)}</div><p class="gridstatus">${state.rows} × ${state.cols} = ${state.rows*state.cols}</p></div>`;}
else if(t.type==='share'){h=`<div class="activitypanel"><span class="bigvalue">${t.total-state.shares.reduce((a,b)=>a+b)} left</span><div class="choices">${state.shares.map((v,i)=>`<button data-share="${i}">Team ${i+1}<br><strong>${v}</strong> balls <span aria-hidden="true">+</span></button>`).join('')}</div><div class="subtools"><button id="share-round">Give 1 to every team</button><button id="resetactivity">Start again</button></div></div>`;}
else if(t.type==='fraction'){h=`<div class="activitypanel"><p class="striplabel">${t.top}/${t.base} of a whole</p><div class="bar" aria-label="${t.top} of ${t.base} equal parts shaded">${Array.from({length:t.base},(_,i)=>`<button tabindex="-1" disabled class="${i<t.top?'on':''}" aria-label="Reference part ${i+1}"></button>`).join('')}</div><p class="striplabel">Your equal fraction</p><div class="bar">${Array.from({length:t.denominator},(_,i)=>`<button data-cell="${i}" class="${state.selected.includes(i)?'on':''}" aria-pressed="${state.selected.includes(i)}" aria-label="Shade part ${i+1} of ${t.denominator}"></button>`).join('')}</div><p class="gridstatus">${state.selected.length}/${t.denominator} shaded</p></div>`;}
else if(t.type==='numberline'){h=`<div class="activitypanel"><div class="numberline">${Array.from({length:t.denominator*2+1},(_,i)=>`<button data-point="${i}" class="${state.point===i?'selected':''}" aria-label="${i} over ${t.denominator}">${i%t.denominator===0?i/t.denominator:`${i}/${t.denominator}`}</button>`).join('')}</div><p class="gridstatus">${state.point==null?'Choose your landing point':`${state.point}/${t.denominator} selected`}</p></div>`;}
else if(['symmetry','compose','area'].includes(t.type)){h=`<div class="activitypanel"><div class="tilegrid">${Array.from({length:32},(_,i)=>{let ref=t.cells?.includes(i),disabled=t.type==='symmetry'&&i%8<4;return `<button data-cell="${i}" class="cell ${ref?'target':''} ${state.selected.includes(i)?'on':''} ${t.type==='symmetry'&&i%8===3?'axis':''}" ${disabled?'disabled':''} style="${ref&&t.type!=='area'?'background:#8062e7;border-color:#7052df':''}" aria-label="Row ${Math.floor(i/8)+1}, column ${i%8+1}${ref?', filled':''}" aria-pressed="${state.selected.includes(i)}"></button>`}).join('')}</div><p class="gridstatus">${t.type==='compose'?`${state.selected.length} of ${t.target} squares placed`:t.type==='area'?`${state.selected.filter(x=>t.cells.includes(x)).length} filled squares counted`:'Match the pattern across the dotted line.'}</p>${t.type==='area'?inputAnswer('square units'):''}</div>`;}
else if(t.type==='chartbuild'){h=`<div class="activitypanel"><p class="striplabel">KEY: 1 block = 2 votes</p>${chart(state.bars.map(v=>v*2),true)}<div class="choices" style="grid-template-columns:repeat(3,1fr)">${state.bars.map((v,i)=>`<div><button data-bar="${i}" data-delta="1" aria-label="Add block to ${['basketball','football','swimming'][i]}">+</button><button data-bar="${i}" data-delta="-1" aria-label="Remove block from ${['basketball','football','swimming'][i]}">−</button></div>`).join('')}</div></div>`;}
else if(t.type==='choice'){h=`<div class="activitypanel">${visual(t)}<div class="choices">${t.choices.map((c,i)=>`<button data-choice="${i}" class="${state.choice===c?'selected':''}" aria-pressed="${state.choice===c}">${esc(c)}</button>`).join('')}</div></div>`;}
else {h=`<div class="activitypanel">${visual(t)}${inputAnswer()}</div>`;}
let old=$('#answer')?.value;$('#activity').innerHTML=h;if(old!==undefined&&$('#answer'))$('#answer').value=old;
$$('[data-cell]').forEach(b=>b.onclick=()=>{if(solved)return;let i=+b.dataset.cell;if(t.type==='area'&&!t.cells.includes(i))return;state.selected=state.selected.includes(i)?state.selected.filter(x=>x!==i):[...state.selected,i];renderActivity()});
$$('[data-order]').forEach(b=>b.onclick=()=>{if(!solved){state.order.push(+b.dataset.order);renderActivity()}});$$('[data-remove]').forEach(b=>b.onclick=()=>{if(!solved){state.order.splice(+b.dataset.remove,1);renderActivity()}});
$$('[data-pv]').forEach(b=>b.onclick=()=>{if(solved)return;let i=+b.dataset.pv;state.pv[i]=Math.max(0,Math.min(9,state.pv[i]+ +b.dataset.delta));renderActivity()});
['rows','cols'].forEach(k=>{if($('#'+k))$('#'+k).onchange=e=>{if(solved)return;state[k]=+e.target.value;let focus=e.target.id;renderActivity();$('#'+focus).focus()}});
$$('[data-share]').forEach(b=>b.onclick=()=>{if(!solved&&state.shares.reduce((a,b)=>a+b)<t.total){state.shares[+b.dataset.share]++;renderActivity()}});
if($('#share-round'))$('#share-round').onclick=()=>{if(!solved&&t.total-state.shares.reduce((a,b)=>a+b)>=t.groups){state.shares=state.shares.map(v=>v+1);renderActivity()}};
$$('[data-point]').forEach(b=>b.onclick=()=>{if(!solved){state.point=+b.dataset.point;renderActivity()}});
$$('[data-choice]').forEach(b=>b.onclick=()=>{if(!solved){state.choice=t.choices[+b.dataset.choice];renderActivity()}});
$$('[data-bar]').forEach(b=>b.onclick=()=>{if(solved)return;let i=+b.dataset.bar;state.bars[i]=Math.max(0,Math.min(6,state.bars[i]+ +b.dataset.delta));renderActivity()});
$$('[data-map]').forEach(b=>b.onclick=()=>{if(solved)return;state.map=+b.dataset.map;renderActivity()});
if($('#addten'))$('#addten').onclick=()=>{if(solved)return;for(let i=0,k=0;i<100&&k<10;i++)if(!state.selected.includes(i)){state.selected.push(i);k++}renderActivity()};
if($('#removeone'))$('#removeone').onclick=()=>{if(!solved){state.selected.pop();renderActivity()}};
if($('#resetactivity'))$('#resetactivity').onclick=()=>{if(!solved){state.selected=[];state.shares=state.shares.map(()=>0);renderActivity()}};
if($('#answer'))$('#answer').onkeydown=e=>{if(e.key==='Enter')check()};
}
function chart(values,blocks=false){return `<div class="barchart" role="img" aria-label="Basketball ${values[0]} votes, football ${values[1]} votes, swimming ${values[2]} votes">${values.map((v,i)=>`<div class="chartcol" style="height:${v*10}px;${blocks?'background:repeating-linear-gradient(to top,#9679e7 0px,#9679e7 18px,#fff 18px,#fff 20px)':''}"><span>${v}</span><small>${['Basketball','Football','Swimming'][i]}</small></div>`).join('')}</div>`}
function visual(t){
if(t.visual==='sequence')return `<div class="sequence">${t.values.join(' · ')} · ?</div>`;
if(t.visual==='split')return `<div class="sequence">(${Math.floor(t.a/10)*10} + ${t.a%10}) × ${t.b}</div>`;
if(t.visual==='regroup')return `<div class="array" style="grid-template-columns:repeat(10,18px)">${Array.from({length:t.tens},()=>'<i style="border-radius:3px;height:24px" title="One ten"></i>').join('')}</div><p class="striplabel">Each block is one ten.</p>`;
if(t.visual==='machine')return `<div class="sequence">2 → ${t.k*2}<br>3 → ${t.k*3}<br>4 → ${t.k*4}</div>`;
if(t.visual==='prices')return `<div class="ordertray"><span class="numbertile">Drink<br>$${(t.a/100).toFixed(2)}</span><span class="numbertile">Snack<br>$${(t.b/100).toFixed(2)}</span></div>`;
if(t.visual==='scale')return `<svg class="geometry" viewBox="0 0 380 160" role="img" aria-label="Scale from zero to ${t.scale.step*10} ${t.scale.unit}. Purple pointer at tick ${t.index}."><line x1="25" y1="80" x2="355" y2="80" stroke="#998aad" stroke-width="3"/>${Array.from({length:11},(_,i)=>`<line x1="${25+i*33}" y1="70" x2="${25+i*33}" y2="90" stroke="#998aad" stroke-width="2"/>${i%5===0?`<text x="${25+i*33}" y="115" text-anchor="middle" font-size="16" fill="#554568">${i*t.scale.step}</text>`:''}`).join('')}<path d="M${25+t.index*33-7},48 L${25+t.index*33+7},48 L${25+t.index*33},66Z" fill="#7052df"/><text x="190" y="150" text-anchor="middle" fill="#554568">${t.scale.unit}</text></svg>`;
if(t.visual==='time')return `<div class="sequence">${clock(t.start)}<br>↓<br>${clock(t.end)}</div>`;
if(t.visual==='angle'){let x=90+120*Math.cos(t.angle*Math.PI/180),y=140-120*Math.sin(t.angle*Math.PI/180);return `<svg class="geometry" viewBox="0 0 320 180" role="img" aria-label="Purple angle ${t.angle} degrees, with grey right-angle reference"><path d="M90 25V140H225" fill="none" stroke="#d4cedf" stroke-width="3"/><path d="M90 118H112V140" fill="none" stroke="#bbb0ca" stroke-width="2"/><path d="M220 140H90L${x} ${y}" fill="none" stroke="#7052df" stroke-width="5" stroke-linecap="round"/></svg>`;}
if(t.visual==='chart')return chart(t.values);
if(t.visual==='chance')return `<div class="ordertray" role="img" aria-label="${t.red} purple and ${t.blue} teal counters">${Array.from({length:t.red+t.blue},(_,i)=>`<span style="width:25px;height:25px;background:${i<t.red?'#7052df':'#177879'};border-radius:50%"></span>`).join('')}</div>`;
if(t.visual==='volume')return `<div class="sequence">A: ${t.a} layers × ${t.b} cubes<br>B: ${t.a*t.b-2} cubes</div>`;
if(t.visual==='map')return `<p class="striplabel">↑ NORTH · KEY: 1 square = ${t.scale} m · Start: A1</p><div style="display:grid;grid-template-columns:repeat(5,1fr);gap:5px">${Array.from({length:15},(_,i)=>`<button data-map="${i}" class="${state.map===i?'primary':''}" aria-pressed="${state.map===i}">${String.fromCharCode(65+i%5)}${Math.floor(i/5)+1}${i===0?' ●':''}</button>`).join('')}</div>`;
return '';}
function pvValue(){return state.pv.reduce((sum,d,i)=>sum+d*10**(4-i),0)}
function rectangle(cells,target){if(cells.length!==target)return false;let rows=cells.map(i=>Math.floor(i/8)),cols=cells.map(i=>i%8);return (Math.max(...rows)-Math.min(...rows)+1)*(Math.max(...cols)-Math.min(...cols)+1)===target;}
function correctness(){let t=task;if(t.type==='hundred'||t.type==='fraction')return state.selected.length===t.answer;if(t.type==='place')return pvValue()===t.answer;if(t.type==='array')return state.rows===t.rows&&state.cols===t.cols;if(t.type==='share')return state.shares.every(x=>x===t.answer);if(t.type==='order'||t.type==='sortsteps')return JSON.stringify(state.order.map(i=>t.values[i]))===JSON.stringify(t.answer);if(t.type==='numberline')return state.point===t.answer;if(t.type==='choice')return state.choice===t.answer;if(t.type==='symmetry')return state.selected.length===t.target.length&&state.selected.every(i=>t.target.includes(i));if(t.type==='compose')return rectangle(state.selected,t.target);if(t.type==='chartbuild')return state.bars.every((v,i)=>v*2===t.values[i]);let raw=$('#answer')?.value.trim().replace(/^\$/,'').replace(/,/g,'');if(!raw||!/^[-+]?\d*\.?\d+$/.test(raw))return false;return Math.abs(Number(raw)-t.answer)<.000001&&(t.visual!=='map'||state.map===t.stepsEast);}
function specificFeedback(){let t=task;
if(t.type==='hundred'){let diff=t.target-state.selected.length;return `You coloured ${state.selected.length} hundredths. ${diff>0?`Try adding ${diff} more`:`Try removing ${-diff}`} to match ${(t.target/100).toFixed(2)}.`;}
if(t.type==='array')return `You made ${state.rows} rows of ${state.cols}. The mission asks for ${t.rows} rows with ${t.cols} in each.`;
if(t.type==='share'){let left=t.total-state.shares.reduce((a,b)=>a+b);return left?`${left} balls still need a team. Keep sharing equally.`:'All balls are used. Check that each team has exactly the same number. You can start the sharing again.';}
if(t.type==='fraction')return `You shaded ${state.selected.length}/${t.denominator}. Compare the amount covered, not just the number of pieces.`;
if(t.type==='place')return `You built ${pvValue().toLocaleString('en-AU')}. Compare one column at a time with ${t.target.toLocaleString('en-AU')}.`;
if(t.type==='symmetry')return 'Check one row at a time. Matching squares must be the same distance from the mirror.';
if(t.type==='compose')return state.selected.length!==t.target?`You used ${state.selected.length} squares. We need ${t.target}.`:'You used the right number. Now close any gaps so every row has the same length.';
if(t.visual==='map')return state.map!==t.stepsEast?'Check your destination too. East is right. Count the squares from A1.':'Your destination is right. Now use the map key to calculate the distance.';
return 'Not quite yet. Let’s make the idea smaller and try it together.';}
function showHelp(wrong=false){help=Math.min(help+1,task.steps.length-1);let html=`<div class="hintbox"><div class="stepmeta">COACH MODE · STEP ${help+1} OF ${task.steps.length}</div><h3>${wrong?'Let’s work through it.':'Start with one small idea.'}</h3>${wrong?`<p>${esc(specificFeedback())}</p>`:''}<p>${esc(task.steps[help])}</p><button id="nexthelp">${help<task.steps.length-1?'Next small step →':'Read this step aloud'}</button>${attempts>=2?'<button id="simpler">Practise the basics</button>':''}</div>`;$('#feedback').innerHTML=html;$('#nexthelp').onclick=()=>help<task.steps.length-1?showHelp():speak(task.steps[help]);if($('#simpler'))$('#simpler').onclick=()=>loadTask(currentSkill,0);}
function check(){if(solved){nextTask();return}let numeric=['number','area'].includes(task.type);if(numeric&&!$('#answer')?.value.trim()){$('#feedback').innerHTML='<div class="hintbox">Put your answer in the answer box first. You can use “Show me how” whenever you need it.</div>';$('#answer')?.focus();return}if(!correctness()){attempts++;record(currentSkill).misses++;showHelp(true);persist();return}
solved=true;let r=record(currentSkill),independent=attempts===0&&help===-1&&task.level>0;r.solved++;r.last=Date.now();if(independent)r.independent.push({sig:task.signature,day:today,session});else r.helped++;r.independent=r.independent.slice(-50);progress.stars+=independent?3:2;progress.completed++;mission++;if(attempts||help>=0)retrySkill=currentSkill;else retrySkill=null;persist();nav();$('#hint').disabled=true;$('#check').innerHTML=mission>=5?'Finish mission ★':'Next challenge →';$('#feedback').innerHTML=`<div class="successbox celebrate"><h3>${independent?'You figured it out!':'You stuck with it!'}</h3><p>${esc(task.steps[task.steps.length-1])}</p><span>+${independent?3:2} stars · ${independent?'Independent discovery':'Learning with support counts too'}</span></div>`;}
function nextTask(){if(mission>=5){missionEnd();return}loadTask(retrySkill||pickSkill(world),retrySkill?1:undefined);}
function missionEnd(){openModal('Mission complete!',`<div class="breakcontent"><div class="breakicon">★</div><h3>Five discoveries. Nicely done, Andre.</h3><p>You now have ${progress.stars} stars.</p><p>Look away from the screen, stretch your arms, and take a sip of water.</p><button class="primary" id="another">Another short mission</button><button id="rest">Rest for now</button></div>`);$('#another').onclick=()=>{closeModal();startWorld(world)};$('#rest').onclick=()=>{closeModal();brainBreak()};}
function openModal(title,html){$('#modaltitle').textContent=title;$('#modalbody').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();}
function closeModal(){$('#modal').close()}
function goalList(parent=false){return WORLDS.map(w=>`<h3>${w.icon} ${w.name}</h3>${SKILLS.filter(s=>s.world===w.id).map(s=>{let r=record(s.id);return `<div class="goalrow"><div><strong>${esc(s.name)}</strong><p>${parent?`${r.solved} completed · ${r.independent.length} independent · ${r.helped} with support`:status(s.id)}</p>${parent?`<code>${esc(s.code)}</code> <span class="status">${status(s.id)}</span>`:''}</div><button data-start="${s.id}">Play this goal →</button></div>`}).join('')}`).join('')}
function bindGoals(){$$('[data-start]').forEach(b=>b.onclick=()=>{let s=SKILLS.find(s=>s.id===b.dataset.start);closeModal();startWorld(s.world,s.id)})}
function parentView(){let explored=SKILLS.filter(s=>record(s.id).solved).length,ind=SKILLS.reduce((a,s)=>a+record(s.id).independent.length,0);openModal('Andre’s learning, at a glance',`<p>Short, hands-on practice mapped to the supplied Victorian Level 4 curriculum. Start with 5 challenges and stop sooner if Andre needs a break.</p><div class="summary"><div><strong>${explored}/${SKILLS.length}</strong>goals explored</div><div><strong>${ind}</strong>independent answers</div><div><strong>${progress.completed}</strong>challenges completed</div></div><p><strong>How to read progress:</strong> “Ready to review” means at least 3 different target-level tasks answered first try, without hints, across 2 different days. It is a prompt for an adult check, not a school pass or a diagnosis. Repeated answers and supported practice do not meet that threshold.</p><p>Some judgement activities have a small set of scenarios, so they remain practice goals. A teacher should check reasoning, written methods and transfer to unfamiliar problems. The drawing pad is a thinking tool, not handwriting recognition.</p><p><strong>Saved on this browser only.</strong> Use Export progress to keep a copy. Another device will start fresh. Closing a page keeps totals, but the current drawing and unfinished challenge are not saved.</p><div class="subtools"><button id="export">Export progress</button><button id="sources">Curriculum & design notes</button></div>${goalList(true)}`);bindGoals();$('#export').onclick=exportProgress;$('#sources').onclick=sources;}
function sources(){openModal('Curriculum & design notes',`<p><strong>Curriculum basis:</strong> Mathematics - Curriculum - Victorian Curriculum.PDF, Level 4, supplied by Rita. It contains VCMNA151–VCMNA164 and the Level 4 overview. The PDF cuts off during the statistics achievement standard and omits detailed measurement and statistics content descriptions. Additional strand mapping follows the <a href="https://victoriancurriculum.vcaa.vic.edu.au/level4" target="_blank" rel="noopener">official Level 4 page</a>. This app follows the supplied curriculum version; confirm Andre’s current school assessment goals with his teacher.</p><p><strong>What informed the game:</strong></p><ul><li><a href="https://dragonbox.com/products/numbers" target="_blank" rel="noopener">DragonBox Numbers</a>: use objects and different activities to make numbers concrete. Its younger target age inspired foundational mechanics, not the difficulty of Andre’s full programme.</li><li><a href="https://polypad.amplify.com/p" target="_blank" rel="noopener">Polypad</a>: fraction bars, number tools, drawing and open exploration.</li><li><a href="https://www.prodigygame.com/main-en/parents/" target="_blank" rel="noopener">Prodigy</a>: short quests, rewards and adjusting practice after difficulty.</li></ul><p>These are design references, not evidence that this app treats ADHD or guarantees a grade. Andre gets one clear task at a time, optional read-aloud, no countdown, calm mode, short missions, movement breaks and supportive retries. The explanations are prepared for each activity, so they work without an AI subscription.</p><p>Some goals still benefit from hands-on adult practice: measure real objects with instruments, conduct a real survey, explain why an answer works and apply ideas in new situations. Use the report to plan those conversations.</p><button id="backparent">Back to progress</button>`);$('#backparent').onclick=parentView;}
function exportProgress(){let data={...progress,exportedAt:new Date().toISOString(),curriculum:'Supplied Victorian Level 4 PDF',goals:SKILLS.map(s=>({...s,status:status(s.id)}))};download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'Andre-maths-progress.json');}
function download(blob,name){let url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function brainBreak(){openModal('A little reset',`<div class="breakcontent"><div class="breakicon">✦</div><h3>Your brain has been working hard.</h3><p>Stand or sit tall.<br>Reach up 5 times.<br>Roll your shoulders 4 times.<br>Take 3 slow breaths.</p><p>No rush. Your progress is safe.</p><button class="primary" id="backplay">I’m ready to play</button></div>`);$('#backplay').onclick=()=>{closeModal();if(mission>=5)startWorld(world)};}
function speak(text){if(!('speechSynthesis' in window)){$('#feedback').innerHTML='<div class="hintbox">Read-aloud is not available in this browser. All instructions are written on the screen.</div>';return}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang='en-AU';u.rate=.86;u.onerror=()=>{$('#savestatus').textContent='Read-aloud unavailable. Try your device’s reading tools.'};speechSynthesis.speak(u)}
$('#stars').onclick=()=>{let badges=[['First discovery',2],['Curious thinker',15],['Problem explorer',40],['Pattern finder',75],['Maths adventurer',120],['Persistent problem solver',200]];openModal('Your discovery badges',`<p>Stars celebrate effort and discoveries. You never lose them.</p><div class="badges">${badges.map(([name,min])=>`<div class="badge ${progress.stars>=min?'earned':''}"><span>${progress.stars>=min?'★':'☆'}</span><strong>${name}</strong><p>${progress.stars>=min?'Earned!':min+' stars'}</p></div>`).join('')}</div>`)};
$('#read').onclick=()=>speak(task.prompt+'. '+task.intro+(help>=0?'. '+task.steps[help]:''));$('#check').onclick=check;$('#hint').onclick=()=>showHelp();$('#skip').onclick=()=>{if(solved){nextTask();return}retrySkill=null;loadTask(currentSkill,task.level)};$('#close').onclick=closeModal;$('#parent').onclick=parentView;$('#break').onclick=brainBreak;$('#goals').onclick=()=>{openModal('Choose your next discovery',`<p>Every world is open. Pick one idea and explore it at your pace.</p>${goalList()}`);bindGoals()};$('#recommended').onclick=()=>{let priorities=['decimal','place','multiply','fraction'];let w=priorities.sort((a,b)=>SKILLS.filter(s=>s.world===a).reduce((x,s)=>x+record(s.id).solved,0)-SKILLS.filter(s=>s.world===b).reduce((x,s)=>x+record(s.id).solved,0))[0];startWorld(w)};$('#calm').onclick=()=>{progress.calm=!progress.calm;applyCalm();persist()};function applyCalm(){document.body.classList.toggle('calm',progress.calm);$('#calm').setAttribute('aria-pressed',String(progress.calm))}
/* Drawings use normalised coordinates so resizing does not distort saved strokes. */
let strokes=[],stroke=null,drawTool='pen',colour='#7151df',drawing=$('#drawing'),ctx=drawing.getContext('2d');
function point(e){let r=drawing.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}
function drawStroke(s){ctx.save();ctx.strokeStyle=s.colour;ctx.fillStyle=s.colour;ctx.lineWidth=s.tool==='eraser'?26:3;ctx.lineCap='round';ctx.lineJoin='round';if(s.tool==='eraser')ctx.globalCompositeOperation='destination-out';let pts=s.points;if(s.tool==='dot'){ctx.beginPath();ctx.arc(pts[0].x*drawing.width,pts[0].y*drawing.height,9,0,Math.PI*2);ctx.fill()}else{ctx.beginPath();ctx.moveTo(pts[0].x*drawing.width,pts[0].y*drawing.height);let p=s.tool==='line'?[pts[pts.length-1]]:pts.slice(1);p.forEach(v=>ctx.lineTo(v.x*drawing.width,v.y*drawing.height));if(pts.length===1)ctx.lineTo(pts[0].x*drawing.width+.1,pts[0].y*drawing.height+.1);ctx.stroke()}ctx.restore()}
function redraw(){ctx.clearRect(0,0,drawing.width,drawing.height);strokes.forEach(drawStroke);if(stroke)drawStroke(stroke)}
function clearDrawing(){strokes=[];stroke=null;redraw()}
drawing.onpointerdown=e=>{e.preventDefault();drawing.setPointerCapture(e.pointerId);stroke={tool:drawTool,colour,points:[point(e)]};redraw()};drawing.onpointermove=e=>{if(!stroke)return;stroke.points.push(point(e));redraw()};function endStroke(){if(stroke){strokes.push(stroke);stroke=null;redraw()}}drawing.onpointerup=endStroke;drawing.onpointercancel=endStroke;
$$('[data-tool]').forEach(b=>b.onclick=()=>{drawTool=b.dataset.tool;$$('[data-tool]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))})});$$('[data-colour]').forEach(b=>b.onclick=()=>{colour=b.dataset.colour;$$('[data-colour]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))});$('#undo').onclick=()=>{strokes.pop();redraw()};$('#clear').onclick=clearDrawing;
applyCalm();startWorld('decimal','decimal-shade');
if(document.modelContext?.registerTool){for(const tool of [{name:'read_learning_progress',description:'Read device-local maths practice progress. This is not a school assessment.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({completed:progress.completed,goals:SKILLS.map(s=>({id:s.id,status:status(s.id)}))})},{name:'start_maths_goal',description:'Open a maths practice goal; this starts a new mission and clears the current working space.',inputSchema:{type:'object',properties:{goalId:{type:'string',enum:SKILLS.map(s=>s.id)}},required:['goalId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{let s=SKILLS.find(s=>s.id===input?.goalId);if(!s)throw new Error('Unknown goal');startWorld(s.world,s.id);return {goalId:s.id,prompt:task.prompt}}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}}
