/* Curriculum map: VCMNA151-164 are transcribed from the supplied Level 4 PDF.
   Other strands use its Level 4 description and achievement standard, without inventing missing codes. */
const WORLDS=[
{id:'decimal',name:'Decimal lab',icon:'.01',title:'Little pieces. Big discoveries.',tag:'NUMBER LAB'},
{id:'place',name:'Number builders',icon:'123',title:'Build numbers with superpowers.',tag:'NUMBER BUILDERS'},
{id:'multiply',name:'Team × times',icon:'×',title:'Stronger together. Multiply it.',tag:'TEAM TIMES'},
{id:'fraction',name:'Fraction studio',icon:'½',title:'Split it. Shade it. See it.',tag:'FRACTION STUDIO'},
{id:'pattern',name:'Pattern detectives',icon:'?',title:'Every pattern leaves a clue.',tag:'DETECTIVE HQ'},
{id:'money',name:'Courtside shop',icon:'$',title:'Your shop. Your smart moves.',tag:'COURTSIDE SHOP'},
{id:'measure',name:'Measure makers',icon:'↔',title:'Size up your next discovery.',tag:'MEASURE MAKERS'},
{id:'time',name:'Time travellers',icon:'◷',title:'Make every minute make sense.',tag:'TIME TRAVELLERS'},
{id:'shape',name:'Shape arcade',icon:'◇',title:'A new angle on your world.',tag:'SHAPE ARCADE'},
{id:'data',name:'Data & chance',icon:'▥',title:'Find the story in the numbers.',tag:'DATA & CHANCE'}];
const SKILLS=[
['decimal-shade','decimal','Build tenths and hundredths','VCMNA159'],['decimal-order','decimal','Order and count decimals','VCMNA159'],['decimal-link','decimal','Link fractions and decimals','VCMNA159'],
['place-partition','place','Partition and regroup five-digit numbers','VCMNA153'],['place-build','place','Represent five-digit numbers','VCMNA152'],['place-order','place','Order large numbers','VCMNA152'],['regroup','place','Partition and regroup','VCMNA153'],['odd','place','Explore odd and even','VCMNA151'],
['array','multiply','Build multiplication facts to 10 × 10','VCMNA155'],['divide','multiply','Share equally and use division facts','VCMNA155, VCMNA156'],['strategy','multiply','Split multiplication into smaller parts','VCMNA156, VCMNA164'],['story','multiply','Solve practical multiplication and division','VCMNA162'],['estimate','multiply','Estimate and check calculations','Number achievement standard'],
['fraction-shade','fraction','Build equivalent fractions','VCMNA157'],['fraction-line','fraction','Count fractions beyond one','VCMNA158'],
['sequence','pattern','Extend sequences of multiples','VCMNA154'],['pattern-rule','pattern','Describe multiplication patterns','VCMNA161'],['balance','pattern','Find missing numbers','VCMNA163'],['algorithm','pattern','Follow and choose calculation steps','VCMNA164'],
['money-total','money','Find total cost and change','VCMNA160'],['money-round','money','Round cash totals to five cents','VCMNA160'],
['measure-scale','measure','Read scales and metric units','VCMMG165'],['area','measure','Compare regular and irregular areas','VCMMG166, VCMMG169'],['volume','measure','Compare volume using equal cubes','VCMMG166'],
['time-duration','time','Work out elapsed time','VCMMG168'],['time-convert','time','Convert time units and use am/pm','VCMMG167, VCMMG168'],
['symmetry','shape','Create a symmetrical pattern','VCMMG173'],['angle','shape','Compare angles to a right angle','VCMMG174'],['compose','shape','Combine and split shapes','VCMMG170'],['map','shape','Read maps, directions and scales','VCMMG172'],
['data-build','data','Build scaled data displays','VCMSP179'],['data-read','data','Compare and evaluate data displays','VCMSP179'],['survey','data','Choose a way to collect data','VCMSP178'],['chance','data','Compare likelihood and outcomes','VCMSP175'],['events','data','Explore independent and exclusive events','VCMSP176, VCMSP177']
,
['decimal-count','decimal','Count forwards in tenths and hundredths','VCMNA159'],['facts','multiply','Recall all facts from 1 × 1 to 10 × 10','VCMNA155'],['shape-properties','shape','Compare 2D shapes and 3D objects','VCMMG171'],['data-compare','data','Choose and evaluate a data display','VCMSP180'],['area-compare','measure','Compare areas in square centimetres','VCMMG166, VCMMG169'],['place-words','place','Connect number words and numerals','VCMNA152'],['fraction-mixed','fraction','Connect mixed numbers and fractions','VCMNA158'],['decimal-reason','decimal','Use decimals in a practical problem','VCMNA159'],['time-ampm','time','Understand am and pm','VCMMG168']
].map(([id,world,name,code])=>({id,world,name,code}));
function makeTask(id,n=0,level=1){
const easy=level===0, v=n%6, pick=a=>a[n%a.length], task={id,level,variant:n};
const result=(o)=>({...task,...o,signature:id+':'+JSON.stringify([o.answer,o.target,o.numerator,o.denominator,o.values,o.prompt])});
const num=(prompt,intro,answer,steps,extra={})=>result({type:'number',prompt,intro,answer,steps,...extra});
const choose=(prompt,intro,choices,answer,steps,extra={})=>result({type:'choice',prompt,intro,choices:[...choices.slice(n%choices.length),...choices.slice(0,n%choices.length)],answer,steps,...extra});
if(id==='decimal-shade'){let target=easy?pick([10,20,30,40,50,60]):pick([35,62,48,75,24,91,16,83]);return result({type:'hundred',prompt:`Build ${(target/100).toFixed(2)} of one whole.`,intro:'This square is one whole. Tap tiny squares to colour them, or add a row of ten.',target,answer:target,steps:['A whole is one complete thing. This whole has 100 equal little squares. Each little square is one hundredth, written 0.01.',`Ten hundredths make one tenth: 10 little squares = 0.10. The first digit after the decimal point counts tenths.`,`For ${(target/100).toFixed(2)}, colour ${Math.floor(target/10)} groups of ten and ${target%10} more little squares. That is ${target} hundredths.`]});}
if(id==='decimal-order'){let values=easy?pick([[.1,.3,.2],[.5,.2,.4],[.6,.3,.1]]):pick([[.8,.35,.08],[.7,.09,.65],[.45,.5,.04],[1.2,1.09,.95],[.6,.06,.56],[.32,.23,.3]]);return result({type:'order',prompt:'Make a decimal stepping path.',intro:'Tap the numbers from smallest to largest. Tap a placed tile to take it back.',values,answer:[...values].sort((a,b)=>a-b),steps:['The decimal point separates whole numbers from parts of a whole. Compare the whole-number parts first.','If the whole numbers match, compare tenths, the first digit after the point. If tenths match, compare hundredths. A missing hundredths digit is zero.',`${[...values].sort((a,b)=>a-b).map(x=>x.toFixed(2)).join(' < ')}. For example, 0.8 is 0.80, so it is bigger than 0.35 even though 8 is less than 35.`]});}
if(id==='decimal-link'){let a=pick([1,2,3,4,5,7]),d=easy?10:pick([10,100,10,100,10,100]);return num(`Turn ${a}/${d} into a decimal.`,`The fraction says ${a} out of ${d} equal parts. Use the drawing space to sketch the parts.`,a/d,[`A fraction names equal parts. The bottom number ${d} says how many parts make one whole. The top number ${a} says how many we have.`,d===10?'Tenths are the first place after the decimal point.':'Hundredths are the second place after the decimal point. We need a zero in the tenths place if there are fewer than ten hundredths.',`${a}/${d} = ${(a/d).toFixed(d===10?1:2)}.`],{unit:'decimal'});}
if(id==='place-partition'){let a=pick([23415,40628,51803,72046,18350,90512]),thousands=Math.floor(a/1000);return num(`Partition ${a.toLocaleString('en-AU')} into thousands and ones.`,`How many complete thousands are in the number? The remaining ${a%1000} ones stay separate.`,thousands,['Partition means split a number into useful parts. A thousand is 1000 ones.',`Ten thousands can be regrouped as 10 thousands. ${Math.floor(a/10000)} ten thousands make ${Math.floor(a/10000)*10} thousands.`,`Add the ${Math.floor(a/1000)%10} extra thousands. ${a.toLocaleString('en-AU')} = ${thousands} thousands + ${a%1000} ones.`],{unit:'complete thousands'});}
if(id==='place-build'){let target=easy?pick([234,305,421,612,152,743]):pick([23415,40628,51803,72046,18350,90512]);return result({type:'place',target,answer:target,prompt:`Build ${target.toLocaleString('en-AU')}.`,intro:'Each column is worth ten times the column to its right. Use + and − to change the digits.',steps:['A digit is a symbol from 0 to 9. Its position tells us its value. Start at the right: ones, tens, hundreds, thousands, ten thousands.','One hundred is ten tens. One thousand is ten hundreds. Zero holds a place when there are none of that size.',`${String(target).padStart(5,'0').split('').map((d,i)=>`${d} ${['ten thousands','thousands','hundreds','tens','ones'][i]}`).join(', ')}. Together they make ${target.toLocaleString('en-AU')}.`]});}
if(id==='place-order'){let b=easy?100:10000,values=[b+v*100+42,b+v*100+24,b+(v+1)*100+2];return result({type:'order',prompt:'Put the numbers in order.',intro:'Build a path from the smallest number to the largest.',values:[values[2],values[0],values[1]],answer:[...values].sort((a,b)=>a-b),steps:['Compare numbers from the largest place, on the left. A five-digit number has ten thousands, thousands, hundreds, tens and ones.','If the first digits match, move one place right until the digits differ.',`The correct order is ${[...values].sort((a,b)=>a-b).join(', ')}.`]});}
if(id==='regroup'){let tens=pick([12,23,34,45,56,67]);return num(`Trade ${tens} tens for hundreds and tens.`,`You have ${tens} bundles of ten. How many complete hundreds can you make?`,Math.floor(tens/10),['Ten ones make one ten. Ten tens make one hundred.',`Group your ${tens} tens into groups of ten. Each full group is one hundred.`,`${tens} tens = ${tens*10} = ${Math.floor(tens/10)} hundreds and ${tens%10} tens.`],{unit:'complete hundreds',visual:'regroup',tens});}
if(id==='odd'){let a=pick([3,4,7,8,5,6]),b=pick([5,7,2,4,8,9]);return choose(`Will ${a} + ${b} be odd or even?`,'Pair up counters in the drawing space. An even number has no counter left over.',['Odd','Even'],(a+b)%2?'Odd':'Even',['Even means everything can be paired. Odd means one is left over.',`${a} is ${a%2?'odd':'even'} and ${b} is ${b%2?'odd':'even'}. Add the two groups.`,`${a} + ${b} = ${a+b}. ${((a+b)%2)?'One counter is left over, so it is odd.':'All the counters pair up, so it is even.'}`]);}
if(id==='array'){let a=easy?pick([2,3,2]):pick([3,4,6,7,8,9,10,5]),b=easy?pick([3,2,4]):pick([4,6,7,8,9,10,5,3]);return result({type:'array',prompt:`Build ${a} rows of ${b}.`,intro:'Use the sliders to arrange your team. Every row needs the same number of dots.',rows:a,cols:b,answer:a*b,steps:['Multiplication means equal groups. An array is a way to arrange equal groups in rows.',`Make ${a} rows. Put ${b} dots in each row. Count in ${b}s as you look at each row.`,`${Array.from({length:a},()=>b).join(' + ')} = ${a*b}. So ${a} × ${b} = ${a*b}.`]});}
if(id==='divide'){let groups=easy?2:pick([3,4,5,6,7,8,9,10]),each=pick([3,5,4,6,2,7,8,9]);return result({type:'share',prompt:`Share ${groups*each} balls among ${groups} teams.`,intro:'Tap each team to give it one ball. Keep sharing until every team has an equal amount and none are left.',groups,total:groups*each,answer:each,steps:['Division means splitting into equal groups. Equal means each group has the same amount.',`Give one ball to each of the ${groups} teams. Keep doing that until all ${groups*each} balls are used.`,`${groups} groups of ${each} make ${groups*each}. So ${groups*each} ÷ ${groups} = ${each}.`]});}
if(id==='strategy'){let a=easy?12:pick([14,23,32,41,26,35]),b=pick([3,4,5,2,3,4]);return num(`Work out ${a} × ${b}.`,'Split the bigger number into tens and ones. Draw a group for each part.',a*b,['You can break a hard multiplication into two smaller multiplications.',`${a} = ${Math.floor(a/10)*10} + ${a%10}. Multiply both parts by ${b}.`,`${Math.floor(a/10)*10} × ${b} = ${Math.floor(a/10)*10*b}, and ${a%10} × ${b} = ${a%10*b}. Add them: ${a*b}.`],{visual:'split',a,b});}
if(id==='story'){let g=easy?2:pick([3,4,5,6,7,8]),each=pick([4,5,6,3,8,7]),div=n%2;return num(div?`${g*each} players make ${g} equal teams. How many on each team?`:`${g} teams each need ${each} cones. How many cones altogether?`,'First picture the story. Draw circles for teams and dots for players or cones.',div?each:g*each,['Ask: do I know the number in each group, or am I finding it?',div?`We know ${g*each} players and ${g} teams. Share the players equally, so use division.`:`There are ${g} equal groups with ${each} in each. We want the total, so use multiplication.`,div?`${g*each} ÷ ${g} = ${each}. Check: ${g} × ${each} = ${g*each}.`:`${g} × ${each} = ${g*each}. Label your answer: ${g*each} cones.`],{unit:div?'players per team':'cones'});}
if(id==='estimate'){let a=pick([19,21,29,31,39,41]),b=pick([4,3,5,2,3,4]),round=Math.round(a/10)*10;return num(`Estimate ${a} × ${b}.`,'Round the first number to the nearest ten, then multiply. An estimate is a useful close answer.',round*b,['An estimate is not an exact answer. It helps us spot answers that are much too big or small.',`${a} is close to ${round}. Use ${round} × ${b}.`,`${round} × ${b} = ${round*b}. The exact answer is ${a*b}, which is close.`],{unit:'estimated total'});}
if(id==='fraction-shade'){let d=easy?4:pick([4,6,8,4,6,8]),a=easy?1:pick([1,1,3,1,2,1]),base=d/2;return result({type:'fraction',prompt:`Make a fraction equal to ${a}/${base}.`,intro:`The top bar shows ${a}/${base}. Shade the same amount in the ${d}-piece bar underneath.`,denominator:d,numerator:a*2,base,top:a,answer:a*2,steps:['A fraction is part of one whole. Equal fractions cover the same amount, even if the pieces are different sizes.',`The top bar is split into ${base} equal pieces. The bottom has ${d}, so each top piece is split into two smaller pieces.`,`${a} larger pieces cover ${a*2} smaller pieces. ${a}/${base} = ${a*2}/${d}.`]});}
if(id==='fraction-line'){let d=easy?2:pick([2,3,4,2,3,4]),a=easy?pick([1,2,3,4]):pick([3,4,5,1,5,7]);return result({type:'numberline',prompt:`Land on ${a}/${d}.`,intro:`Every jump is 1/${d}. Tap the landing point on the number line.`,denominator:d,answer:a,steps:[`The bottom number ${d} tells us that ${d} equal jumps make one whole. Each jump is 1/${d}.`,`Start at zero and count ${a} jumps of 1/${d}. It is okay to go past one whole.`,`${a}/${d} is ${Math.floor(a/d)} whole${Math.floor(a/d)===1?'':'s'} and ${a%d}/${d}. Tap jump number ${a}.`]});}
if(id==='sequence'){let k=easy?3:pick([3,4,6,7,8,9]),start=(v+1)*k;return num('Find the next stepping stone.',`Each step adds the same amount. Say the numbers or draw the jumps.`,start+4*k,['A sequence is a list that follows a rule. Find how much is added each time.',`${start+k} − ${start} = ${k}, so the rule is add ${k}.`,`${start+3*k} + ${k} = ${start+4*k}. These numbers are multiples of ${k}.`],{visual:'sequence',values:[start,start+k,start+2*k,start+3*k]});}
if(id==='pattern-rule'){let k=pick([3,4,6,7,8,9]);return choose('Crack the number machine.','Look at what happens to every input.',[`Multiply by ${k}`,`Add ${k}`,`Multiply by ${k+1}`],`Multiply by ${k}`,['A rule must work for every input, not just the first one.',`Input 2 becomes ${2*k}; input 3 becomes ${3*k}. Try the same operation on both.`,`Multiplying by ${k} works: 2 × ${k} = ${2*k} and 3 × ${k} = ${3*k}.`],{visual:'machine',k});}
if(id==='balance'){let a=pick([12,23,18,31,24,42]),b=pick([40,57,50,60,70,80]),c=pick([9,19,12,11,16,18]);return num(`${a} + □ = ${b} − ${c}`,'The equals sign means both sides have the same value. Find the missing number.',b-c-a,['An equation is a balance: the total on the left must equal the total on the right.',`First work out the right side: ${b} − ${c} = ${b-c}.`,`Now find the gap: ${b-c} − ${a} = ${b-c-a}. Check: ${a} + ${b-c-a} = ${b-c}.`]);}
if(id==='algorithm'){let a=pick([23,34,42,15,26,31]),b=pick([3,2,4,5,3,2]),t=Math.floor(a/10)*10,u=a%10;return result({type:'sortsteps',prompt:`Plan a way to solve ${a} × ${b}.`,intro:'Tap the steps in the order you would use them. An algorithm is a plan of small steps.',values:[`Add the two products`,`Split ${a} into ${t} and ${u}`,`Multiply ${t} and ${u} by ${b}`],answer:[`Split ${a} into ${t} and ${u}`,`Multiply ${t} and ${u} by ${b}`,`Add the two products`],steps:['First split the number so the parts are easier to work with.',`Then multiply each part: ${t} × ${b} = ${t*b}; ${u} × ${b} = ${u*b}.`,`Finally add ${t*b} + ${u*b} = ${a*b}. The order matters because later steps use earlier results.`]});}
if(id==='money-total'){let a=pick([225,340,465,175,520,685]),b=pick([150,225,310,260,145,230]),paid=1000,change=n%2;return num(change?`Pay $10.00. What change do you get?`:'What do the two items cost together?',`A drink costs $${(a/100).toFixed(2)}. A snack costs $${(b/100).toFixed(2)}.`,(change?paid-a-b:a+b)/100,['One dollar is 100 cents. Working in cents can make the calculation easier.',`${a} cents + ${b} cents = ${a+b} cents, or $${((a+b)/100).toFixed(2)}.`,change?`Change is what comes back. 1000 − ${a+b} = ${paid-a-b} cents, so $${((paid-a-b)/100).toFixed(2)}.`:`Convert cents back to dollars: ${a+b} cents = $${((a+b)/100).toFixed(2)}.`],{unit:'dollars',visual:'prices',a,b});}
if(id==='money-round'){let cents=pick([432,468,721,684,957,813]),rounded=Math.round(cents/5)*5;return num(`The cash total is $${(cents/100).toFixed(2)}. What do you pay?`,'For this Australian cash purchase, round the final total to the nearest 5 cents.',rounded/100,['Cash totals are rounded because the smallest Australian coin is 5 cents. Round the total, not every item.',`Nearby multiples of 5 cents are ${Math.floor(cents/5)*5} cents and ${Math.ceil(cents/5)*5} cents. Which is closer?`,`${cents} cents rounds to ${rounded} cents. Pay $${(rounded/100).toFixed(2)} in cash.`],{unit:'dollars'});}
if(id==='measure-scale'){let scale=pick([{unit:'cm',step:2,label:'length'},{unit:'g',step:100,label:'mass'},{unit:'mL',step:50,label:'capacity'},{unit:'°C',step:5,label:'temperature'}]),index=pick([3,5,7,4,6,8]);return num(`Read the ${scale.label} scale.`,'Each gap has the same value. Find the value at the purple marker.',index*scale.step,['A scale has equally spaced marks. The unit tells us what is measured.',`From 0 to ${scale.step*5} there are five equal gaps. Each gap is worth ${scale.step} ${scale.unit}.`,`The marker is ${index} gaps from zero: ${index} × ${scale.step} = ${index*scale.step} ${scale.unit}.`],{visual:'scale',scale,index,unit:scale.unit});}
if(id==='area'){let cells=pick([[0,1,2,3,8,9,10,11],[0,1,2,8,9,16,17],[0,1,2,3,8,9,10,11,16,17,18,19],[0,1,8,9,16,17],[0,1,2,8,9,10,16,17],[0,1,2,3,4,8,9,10,11,12]]);return result({type:'area',prompt:'Measure this shape with square tiles.',intro:'Tap every coloured square as you count. Then enter the area. Each little square is one square unit.',cells,answer:cells.length,steps:['Area is how much flat space a shape covers. Use equal-sized squares so the measure is fair.','Count each filled square exactly once. Empty squares do not belong to the shape.',`This shape covers ${cells.length} squares, so its area is ${cells.length} square units.`]});}
if(id==='volume'){let a=pick([2,3,4,2,3,4]),b=pick([3,2,2,4,3,3]);return num(`Which stack has more volume? How many more cubes?`,`Stack A has ${a} layers with ${b} cubes in each. Stack B has ${a*b-2} cubes. All cubes are the same size.`,2,['Volume is the space a solid object takes up. Compare using cubes of the same size.',`Stack A: ${a} × ${b} = ${a*b} cubes. Stack B: ${a*b-2} cubes.`,`Stack A has ${a*b} − ${a*b-2} = 2 more cubes, so it has more volume.`],{unit:'more cubes in A',visual:'volume',a,b});}
if(id==='time-duration'){let start=pick([9*60+40,14*60+20,10*60+45,11*60+35,15*60+50,8*60+25]),duration=pick([45,55,40,50,35,65]);return num(`Training starts at ${clock(start)} and ends at ${clock(start+duration)}.`,'How many minutes does it last? Draw a number line and jump through the hour.',duration,['Duration means how much time passes from start to finish. One hour has 60 minutes, not 100.',`From ${clock(start)} to ${clock(Math.ceil(start/60)*60)} is ${60-start%60} minutes.`,`Then count to ${clock(start+duration)}. The whole time is ${duration} minutes.`],{unit:'minutes',visual:'time',start,end:start+duration});}
if(id==='time-convert'){let hours=pick([1,2,3,1,2,3]),mins=pick([15,20,30,45,10,5]);return num(`Convert ${hours} hour${hours>1?'s':''} ${mins} minutes.`,`How many minutes is that altogether?`,hours*60+mins,['An hour is made of 60 minutes. Convert hours to minutes before adding.',`${hours} × 60 = ${hours*60} minutes.`,`Add the extra ${mins}: ${hours*60} + ${mins} = ${hours*60+mins} minutes.`],{unit:'minutes'});}
if(id==='symmetry'){let cells=pick([[1,2,9,17,18,25],[0,8,9,16,24,25],[2,10,17,18,26],[1,9,10,17,25,26],[0,1,9,16,17,25],[2,3,10,18,19,26]]),target=cells.map(x=>Math.floor(x/8)*8+7-x%8);return result({type:'symmetry',prompt:'Complete the mirror pattern.',intro:'The dotted line is a mirror. Tap squares on the right to match the purple pattern.',cells,target,answer:target,steps:['A symmetrical pattern matches when folded along the mirror line. Each square needs a partner.','Count how far a purple square is from the middle line. Put its partner the same distance away on the other side.','Stay in the same row. The nearest left column matches the nearest right column; the farthest matches the farthest.']});}
if(id==='angle'){let angle=pick([45,90,120,60,150,30]);return choose('Compare this angle to a right angle.','An angle measures a turn. A right angle is a quarter turn, like a square corner.',['Smaller than a right angle','Equal to a right angle','Larger than a right angle'],angle<90?'Smaller than a right angle':angle===90?'Equal to a right angle':'Larger than a right angle',['A right angle measures 90 degrees. The pale square corner shows the reference.','Compare the opening between the two purple arms with the square corner.',`${angle}° is ${angle<90?'smaller than':angle===90?'equal to':'larger than'} 90°.`],{visual:'angle',angle});}
if(id==='compose'){let cols=pick([2,3,4,5,2,3]);return result({type:'compose',prompt:`Make a rectangle from ${cols*2} squares.`,intro:'Tap the grid to make a solid rectangle using all the squares. There can be more than one correct shape.',target:cols*2,answer:cols*2,steps:['A rectangle has four straight sides and four square corners. A square is also a special rectangle.',`Use ${cols*2} touching squares with no gaps. Every row of your rectangle must have the same length.`,`One possible rectangle has 2 rows of ${cols} squares. Other solid rectangles using ${cols*2} squares also work.`]});}
if(id==='map'){let steps=pick([2,3,4,2,3,4]),scale=pick([50,100,25,50,25,100]);return num(`Travel ${steps} squares east from the start.`,'Tap your destination on the map, then enter the real distance. North is up; east is right.',steps*scale,[`The map key says one square represents ${scale} metres. Start at A1. East means right.`,`Move ${steps} squares right, staying in row 1. Count the gaps you travel.`,`${steps} × ${scale} = ${steps*scale} metres.`],{visual:'map',stepsEast:steps,scale,unit:'metres'});}
if(id==='data-build'){let vals=pick([[4,6,2],[6,2,8],[8,4,6],[2,8,4],[6,8,2],[4,2,6]]);return result({type:'chartbuild',prompt:'Build the team survey graph.',intro:`Votes: basketball ${vals[0]}, football ${vals[1]}, swimming ${vals[2]}. Each block represents 2 votes. Use + and − to build the bars.`,values:vals,answer:vals,steps:['A graph shows data, which means information we have collected. Each sport needs its own bar.','The key says one block = 2 votes. Divide the votes by 2 to find the number of blocks.',`Use ${vals[0]/2} blocks for basketball, ${vals[1]/2} for football and ${vals[2]/2} for swimming.`]});}
if(id==='data-read'){let vals=pick([[4,8,6],[6,4,10],[8,12,4],[2,6,8],[10,4,6],[6,10,2]]);return num('How many votes altogether?','Read the bar graph. The labels above the bars show the number of votes, not the number of blocks.',vals.reduce((a,b)=>a+b),['A bar graph compares categories. The height of a bar represents how many votes that sport received.','To find the total, add all three bars.',`${vals.join(' + ')} = ${vals.reduce((a,b)=>a+b)} votes. Bars are helpful here because their heights are easy to compare.`],{visual:'chart',values:vals,unit:'votes'});}
if(id==='survey')return choose('Find your class’s favourite sport.','You want each student to have one equal say. What is the fairest way to collect the data?',['Ask every student once','Ask only basketball players','Count your own favourite five times'],'Ask every student once',['Data means information. A survey asks people a question and records their answers.','If you only ask one group, you may miss what others like. Counting someone repeatedly gives them extra votes.','Ask each student once, record one answer each, then display totals in a labelled bar graph.']);
if(id==='chance'){let red=pick([3,1,5,2,4,6]),blue=pick([1,4,2,5,1,3]);return choose('Which colour is more likely? ',`A bag holds ${red} purple counters and ${blue} teal counters. You pick one without looking.`,['Purple','Teal','Equally likely'],red>blue?'Purple':red<blue?'Teal':'Equally likely',['An outcome is something that can happen. Here the possible colours are purple and teal.','More counters of one colour give you more ways to pick that colour. More likely does not mean certain.',`${red>blue?'Purple':'Teal'} has more counters. It is more likely, but either colour could be picked.`],{visual:'chance',red,blue});}
if(id==='events'){let exclusive=n%2===0;return choose(exclusive?'Can one die roll be both 2 and 5?':'Does a coin landing heads change the next fair coin toss?',exclusive?'A normal die has the numbers 1 to 6. You roll it once.':'Imagine tossing a fair coin twice. Each toss starts fresh.',exclusive?['Yes, both can happen together','No, they cannot happen together']:['Yes, tails must be next','No, either side is still possible'],exclusive?'No, they cannot happen together':'No, either side is still possible',exclusive?['A single roll lands on just one face.','Landing on 2 and landing on 5 cannot happen on that same roll.','These events are mutually exclusive. That means they cannot happen together.']:['Independent events do not change each other’s chances.','The coin does not remember its last result. A head does not force a tail next.','The two tosses are independent. Heads and tails are both still possible on the next toss.']);}

if(id==='decimal-count'){let step=easy?10:pick([10,1,10,1,10,1]),start=pick([20,27,70,58,90,98]);return num('Keep the decimal count going.','Find the size of the jump. What number comes next?',(start+3*step)/100,['Each decimal is part of a whole. Write two digits after the point to make the places easy to compare.',`The jump is ${(step/100).toFixed(2)} each time. That is ${step===10?'one tenth':'one hundredth'}.`,`Add ${(step/100).toFixed(2)} to ${((start+2*step)/100).toFixed(2)}. The next number is ${((start+3*step)/100).toFixed(2)}.`],{visual:'sequence',values:[start,start+step,start+2*step].map(x=>(x/100).toFixed(2))});}
if(id==='facts'){let a=easy?2:1+n%10,b=easy?1+n%5:1+Math.floor(n/10)%10;return num(`${a} × ${b} = ?`,'Try recalling the fact. If you need to, draw equal groups or ask for a small step.',a*b,['Multiplication counts equal groups. You do not have to guess.',`Picture ${a} groups, each with ${b}. Count in ${b}s, once for each group.`,`${a} × ${b} = ${a*b}. The related division fact is ${a*b} ÷ ${a} = ${b}.`]);}
if(id==='shape-properties'){let shapes=[['cube','faces',6,'A cube is a 3D solid with six flat square faces.'],['triangle','sides',3,'A triangle is a flat 2D shape with three straight sides.'],['square','vertices',4,'A vertex is a corner. A square has four corners.'],['cube','edges',12,'An edge is where two faces meet. A cube has four edges on top, four on the bottom and four joining them.'],['rectangular prism','faces',6,'A rectangular prism is a box-shaped solid with six rectangular faces.'],['triangle','vertices',3,'A triangle has three corners. The maths word for corners is vertices.']],q=pick(shapes);return num(`How many ${q[1]} does a ${q[0]} have?`,'Draw the shape or use a real box to help you count.',q[2],['2D shapes are flat. 3D objects have depth as well as length and width.',q[3],`A ${q[0]} has ${q[2]} ${q[1]}.`],{unit:q[1]});}
if(id==='data-compare'){let q=pick([['compare the most popular sport','A labelled bar graph','Bar heights make category totals easy to compare.'],['find each student’s exact answer','A table of individual responses','A table keeps the individual answers so you can look each one up.'],['compare how spread out the votes are','A labelled bar graph','Bar heights show whether categories have similar totals or very different totals.']]);return choose(`Which display helps you ${q[0]}?`,'Choose the display that fits the question. The best display depends on what you want to find out.',['A labelled bar graph','A table of individual responses','An unlabelled picture'],q[1],['A data display organises information so it is easier to understand.','Bars make comparisons visible. A table keeps exact records. Labels explain what the data means.',q[2]]);}
if(id==='area-compare'){let a=pick([3,4,5,3,4,5]),b=2,other=a*b-2;return num(`How much larger is court A?`,`A covers ${a} rows of ${b} one-centimetre squares. B covers ${other} one-centimetre squares.`,2,['Area measures flat space. A 1 cm by 1 cm square covers one square centimetre, written cm².',`Court A covers ${a} × ${b} = ${a*b} cm². Court B covers ${other} cm².`,`Subtract to compare: ${a*b} − ${other} = 2 cm².`],{unit:'square centimetres larger'});}
if(id==='place-words'){let pair=pick([['twenty-three thousand, four hundred and fifteen',23415],['forty thousand, six hundred and twenty-eight',40628],['fifty-one thousand, eight hundred and three',51803],['seventy-two thousand and forty-six',72046],['eighteen thousand, three hundred and fifty',18350],['ninety thousand, five hundred and twelve',90512]]);return num(`Write ${pair[0]} in digits.`,'Break the words into thousands, hundreds, tens and ones.',pair[1],['Number words name the size of the parts. “Thousand” means groups of one thousand.',`This number has ${Math.floor(pair[1]/1000)} thousands and ${pair[1]%1000} more. Use zeros for empty places.`,`The numeral is ${pair[1].toLocaleString('en-AU')}.`]);}
if(id==='fraction-mixed'){let d=pick([2,3,4,2,3,4]),whole=easy?1:pick([1,2,1,3,1,2]),part=pick([1,1,3,1,2,1]);return num(`Write ${whole} and ${part}/${d} as a fraction.` ,`Keep ${d} as the bottom number. How many ${d===2?'halves':d===3?'thirds':'quarters'} altogether?`,whole*d+part,[`One whole contains ${d} pieces of size 1/${d}.`,`The ${whole} whole${whole===1?'':'s'} contain ${whole*d} pieces. Add the ${part} extra pieces.`,`${whole} and ${part}/${d} = ${whole*d+part}/${d}. The top number is ${whole*d+part}.`],{unit:`top number, over ${d}`});}
if(id==='decimal-reason'){let a=pick([45,65,75,35,85,55]),b=pick([20,15,10,25,5,30]);return num(`A ribbon is ${(a/100).toFixed(2)} m long. Cut off ${(b/100).toFixed(2)} m.`,'How many metres are left? Draw the whole length, then cross out the cut piece.',(a-b)/100,['Both measurements use metres. The two digits after the point count hundredths of a metre.',`Start with ${a} hundredths. Remove ${b} hundredths. ${a} − ${b} = ${a-b}.`,`${a-b} hundredths of a metre = ${((a-b)/100).toFixed(2)} m.`],{unit:'metres'});}
if(id==='time-ampm'){let q=pick([['Breakfast at 7:30','am','Breakfast is in the morning, before midday.'],['Training at 4:00 in the afternoon','pm','Afternoon is after midday.'],['Lunch at midday, 12:00','pm','Midday is 12 pm. Midnight is 12 am.'],['Bedtime at 8:00 at night','pm','Evening is after midday.'],['Waking up at 6:45','am','Morning is before midday.'],['Midnight, 12:00','am','Midnight starts the new day and is written 12 am.']]);return choose(q[0]+'… am or pm?','am is from midnight until before midday. pm is from midday until before midnight.',['am','pm'],q[1],['A day has 24 hours. am and pm tell us which half of the day we mean.',q[2],`Write ${q[1]}.`]);}

throw new Error('Unknown skill '+id);
}
function clock(m){return `${Math.floor(m/60)%12||12}:${String(m%60).padStart(2,'0')} ${m>=720?'pm':'am'}`;}
if(typeof module!=='undefined')module.exports={makeTask,SKILLS,WORLDS};
